{
  "id": "EUVD-2021-0270",
  "enisaUuid": "fd40ab88-d18d-3db9-9872-5bbef2f4bc16",
  "description": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can trigger a heap buffer overflow in `tf.raw_ops.QuantizedResizeBilinear` by manipulating input values so that float rounding results in off-by-one error in accessing image elements. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/44b7f486c0143f68b56c34e2d01e146ee445134a/tensorflow/core/kernels/quantized_resize_bilinear_op.cc#L62-L66) computes two integers (representing the upper and lower bounds for interpolation) by ceiling and flooring a floating point value. For some values of `in`, `interpolation->upper[i]` might be smaller than `interpolation->lower[i]`. This is an issue if `interpolation->upper[i]` is capped at `in_size-1` as it means that `interpolation->lower[i]` points outside of the image. Then, in the interpolation code(https://github.com/tensorflow/tensorflow/blob/44b7f486c0143f68b56c34e2d01e146ee445134a/tensorflow/core/kernels/quantized_resize_bilinear_op.cc#L245-L264), this would result in heap buffer overflow. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.",
  "datePublished": "May 14, 2021, 8:15:00 PM",
  "dateUpdated": "Aug 27, 2021, 3:22:26 AM",
  "baseScore": 2.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:L",
  "references": [
    "https://github.com/tensorflow/tensorflow/commit/f851613f8f0fb0c838d160ced13c134f778e3ce7",
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jfp7-4j67-8r3q",
    "https://nvd.nist.gov/vuln/detail/CVE-2021-29529",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-457.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-655.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-166.yaml",
    "https://www.suse.com/security/cve/CVE-2021-29529.html",
    "https://security.archlinux.org/CVE-2021-29529"
  ],
  "aliases": [
    "CVE-2021-29529",
    "GHSA-jfp7-4j67-8r3q",
    "PYSEC-2021-457"
  ],
  "assigner": "GitHub_M",
  "epss": 0.05,
  "enisaIdProduct": [
    {
      "id": "0b015250-0c34-3d78-b8f9-9d8263852e08",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "2.4.0, < 2.4.2"
    },
    {
      "id": "9760d525-e824-32bb-8eec-4907b744ee43",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "< 2.1.4"
    },
    {
      "id": "ad2a8dd0-3b66-3d25-bd43-f8d480e12189",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "2.2.0, < 2.2.3"
    },
    {
      "id": "ed48def0-d613-3439-bf9d-b4f9412a3e3e",
      "product": {
        "name": "tensorflow"
      },
      "product_version": "2.3.0, < 2.3.3"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "8980a374-a58b-3354-a431-60d8b8532c95",
      "vendor": {
        "name": "tensorflow"
      }
    }
  ]
}