{
  "id": "EUVD-2025-16736",
  "enisaUuid": "65ce8d49-172f-3551-affa-e24fe0221ca7",
  "description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile\u00a0module to extract untrusted tar archives using TarFile.extractall()\u00a0or TarFile.extract()\u00a0using the filter=\u00a0parameter with a value of \"data\"\u00a0or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter \u00a0for more information.\n\nNote that for Python 3.14 or later the default value of filter=\u00a0changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.",
  "datePublished": "Jun 3, 2025, 12:58:50 PM",
  "dateUpdated": "Jul 7, 2025, 5:36:26 PM",
  "baseScore": 9.4,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L",
  "references": [
    "https://github.com/python/cpython/issues/135034",
    "https://github.com/python/cpython/pull/135037",
    "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/",
    "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a",
    "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a",
    "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f",
    "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da",
    "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01",
    "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9",
    "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e",
    "https://nvd.nist.gov/vuln/detail/CVE-2025-4517",
    "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a",
    "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1"
  ],
  "aliases": [
    "CVE-2025-4517"
  ],
  "assigner": "PSF",
  "epss": 0.17,
  "enisaIdProduct": [
    {
      "id": "135dbff4-c233-3ca2-adab-9c0b6c9b41b1",
      "product": {
        "name": "CPython"
      },
      "product_version": "0 <3.14.0b2"
    },
    {
      "id": "3dd0836b-0140-3c8d-8a89-61b7a9f4917f",
      "product": {
        "name": "CPython"
      },
      "product_version": "3.10.0 <3.10.18"
    },
    {
      "id": "79a2e533-b4e1-3308-9605-9de4b7361adb",
      "product": {
        "name": "CPython"
      },
      "product_version": "3.13.0 <3.13.4"
    },
    {
      "id": "8887e016-6ae8-3c47-afed-9848ec72147c",
      "product": {
        "name": "CPython"
      },
      "product_version": "3.11.0 <3.11.13"
    },
    {
      "id": "b0ff8359-3712-369f-9e59-0efb316ac0dd",
      "product": {
        "name": "CPython"
      },
      "product_version": "3.14.0a1 <3.14.0"
    },
    {
      "id": "c4cd6537-2b7a-3441-af9d-1547e910ee7f",
      "product": {
        "name": "CPython"
      },
      "product_version": "0 <3.9.23"
    },
    {
      "id": "e8949c6a-48bb-388b-9b4f-1aaa437b3437",
      "product": {
        "name": "CPython"
      },
      "product_version": "3.12.0 <3.12.11"
    },
    {
      "id": "eaec3b45-4198-3feb-8d94-a0b34240b4e1",
      "product": {
        "name": "CPython"
      },
      "product_version": "3.14.0a1 <3.14.0b3"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "a6f9079f-3c95-3f55-b94a-517135e355d7",
      "vendor": {
        "name": "Python Software Foundation"
      }
    }
  ]
}