{
  "id": "EUVD-2021-9375",
  "enisaUuid": "139d8210-270f-3976-9000-aefde26c3710",
  "description": "An issue has been discovered in GitLab CE/EE affecting all versions starting with 12.8. Under a special condition it was possible to access data of an internal repository through project fork done by a project member.",
  "datePublished": "Jul 6, 2021, 8:30:47 PM",
  "dateUpdated": "Aug 3, 2024, 6:37:17 PM",
  "baseScore": 5.9,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
  "references": [
    "https://security.archlinux.org/CVE-2021-22229",
    "https://gitlab.com/gitlab-org/gitlab/-/issues/332609",
    "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22229.json"
  ],
  "aliases": [
    "CVE-2021-22229",
    "GSD-2021-22229"
  ],
  "assigner": "GitLab",
  "epss": 0.2,
  "enisaIdProduct": [
    {
      "id": "1bd81b4a-ff5b-3a0a-93cf-5591d6d71815",
      "product": {
        "name": "GitLab"
      },
      "product_version": "12.8, <13.11.6"
    },
    {
      "id": "376ade5a-02ac-31fd-965f-6003506f46cb",
      "product": {
        "name": "GitLab"
      },
      "product_version": "13.12, <13.12.6"
    },
    {
      "id": "89a9f70f-cdcb-38e2-9f43-ffd853a22320",
      "product": {
        "name": "GitLab"
      },
      "product_version": "14.0, <14.0.2"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "82b175f8-68ba-3618-8a91-f2d78af621cf",
      "vendor": {
        "name": "GitLab"
      }
    }
  ]
}