{
  "id": "EUVD-2025-16536",
  "description": "django-helpdesk Allows Sensitive Data Exposure",
  "datePublished": "May 31, 2025, 3:30:33 AM",
  "dateUpdated": "Jun 4, 2025, 1:30:24 AM",
  "baseScore": 5.1,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
  "references": [
    "https://nvd.nist.gov/vuln/detail/CVE-2018-25111",
    "https://github.com/django-helpdesk/django-helpdesk/issues/591",
    "https://github.com/django-helpdesk/django-helpdesk/pull/1120",
    "https://github.com/django-helpdesk/django-helpdesk/releases/tag/v1.0.0",
    "https://github.com/django-helpdesk/django-helpdesk/commit/f872ec252769bee5a88b06d07d3634e580c67bcc",
    "https://github.com/pypa/advisory-database/tree/main/vulns/django-helpdesk/PYSEC-2025-44.yaml"
  ],
  "aliases": [
    "CVE-2018-25111",
    "GHSA-m4jx-m5hg-qrxx"
  ],
  "assigner": "mitre",
  "epss": 0.0,
  "enisaIdProduct": [
    {
      "id": "c0a240a4-f7f2-3379-b818-f0a42e31ad56",
      "product": {
        "name": "django-helpdesk"
      },
      "product_version": "0 <1.0.0"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "2a2f6ffb-e735-3ebc-989f-dce5961d2173",
      "vendor": {
        "name": "django-helpdesk Project"
      }
    }
  ],
  "cve": "CVE-2018-25111"
}
