{
  "id": "EUVD-2017-14700",
  "enisaUuid": "848f8a24-dbb2-34f2-ac8b-17cd7da5d9e3",
  "description": "An error in the lha_read_file_header_1() function (archive_read_support_format_lha.c) in libarchive 3.2.2 allows remote attackers to trigger an out-of-bounds read memory access and subsequently cause a crash via a specially crafted archive.",
  "datePublished": "May 14, 2022, 1:54:40 AM",
  "dateUpdated": "Apr 20, 2025, 3:31:55 AM",
  "baseScore": 7.5,
  "baseScoreVersion": "3.0",
  "baseScoreVector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://www.suse.com/security/cve/CVE-2017-5601.html",
    "https://ubuntu.com/security/CVE-2017-5601",
    "https://advisories.mageia.org/CVE-2017-5601.html",
    "https://secunia.com/secunia_research/2017-3/",
    "https://github.com/libarchive/libarchive/commit/98dcbbf0bf4854bf987557e55e55fff7abbf3ea9",
    "http://www.securityfocus.com/bid/95837",
    "https://lists.debian.org/debian-lts-announce/2018/11/msg00037.html",
    "http://www.securitytracker.com/id/1037974",
    "https://nvd.nist.gov/vuln/detail/CVE-2017-5601"
  ],
  "aliases": [
    "CVE-2017-5601",
    "GSD-2017-5601"
  ],
  "assigner": "mitre",
  "epss": 0.52,
  "enisaIdProduct": [
    {
      "id": "a130b2bb-2a7c-33d0-a471-2fa00a85afb9",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "271b0035-f9ff-3e21-bf5b-83e272f672d5",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}