{
  "id": "EUVD-2025-31131",
  "enisaUuid": "b74718d0-8fb1-39e0-922f-095716512aac",
  "description": "A syntax error in the component proxy_tensor.py of pytorch v2.7.0 allows attackers to cause a Denial of Service (DoS).",
  "datePublished": "Sep 25, 2025, 6:30:34 PM",
  "dateUpdated": "Sep 29, 2025, 6:33:12 PM",
  "baseScore": 7.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://github.com/pytorch/pytorch/issues/151432",
    "https://github.com/pytorch/pytorch/pull/154645",
    "https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc",
    "https://nvd.nist.gov/vuln/detail/CVE-2025-55553"
  ],
  "aliases": [
    "CVE-2025-55553"
  ],
  "assigner": "mitre",
  "epss": 0.05,
  "enisaIdProduct": [
    {
      "id": "5bfac406-567c-31ec-80d8-e714a313f9fe",
      "product": {
        "name": "n/a"
      },
      "product_version": "n/a"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "c149f219-e6da-342e-85d2-42d757a6666f",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}