{
  "id": "EUVD-2016-10396",
  "enisaUuid": "8142548c-8627-319f-bbd6-9216bc909406",
  "description": "openshift before versions 3.3.1.11, 3.2.1.23, 3.4 is vulnerable to a flaw when a volume fails to detach, which causes the delete operation to fail with 'VolumeInUse' error. Since the delete operation is retried every 30 seconds for each volume, this could lead to a denial of service attack as the number of API requests being sent to the cloud-provider exceeds the API's rate-limit.",
  "datePublished": "Apr 16, 2018, 2:00:00 PM",
  "dateUpdated": "Aug 6, 2024, 2:59:02 AM",
  "baseScore": 4.3,
  "baseScoreVersion": "3.0",
  "baseScoreVector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
  "references": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-9592",
    "http://www.securityfocus.com/bid/94991"
  ],
  "aliases": [
    "CVE-2016-9592",
    "GSD-2016-9592"
  ],
  "assigner": "redhat",
  "epss": 0.32,
  "enisaIdProduct": [
    {
      "id": "495828d7-c796-37f6-b410-7448fc907fb5",
      "product": {
        "name": "OpenShift"
      },
      "product_version": "openshift 3.2.1.23"
    },
    {
      "id": "7d94c34e-477b-3ade-bde3-a9febc778311",
      "product": {
        "name": "OpenShift"
      },
      "product_version": "openshift 3.4"
    },
    {
      "id": "dffb8c97-3d0e-3f7b-963d-21c3a04edccb",
      "product": {
        "name": "OpenShift"
      },
      "product_version": "openshift 3.3.1.11"
    }
  ],
  "enisaIdVendor": [
    {
      "id": "d4dba571-d1f7-30a7-ab39-e0abd897f56e",
      "vendor": {
        "name": "unspecified"
      }
    }
  ]
}