{
  "id": "EUVD-2020-0654",
  "enisaUuid": "c33c9716-054e-3c4f-a9c7-664a122c70f9",
  "description": "A denial of service vulnerability exists in Fastify v2.14.1 and v3.0.0-rc.4 that allows a malicious user to trigger resource exhaustion (when the allErrors option is used) with specially crafted schemas.",
  "datePublished": "Jul 30, 2020, 12:53:02 PM",
  "dateUpdated": "Aug 4, 2024, 9:56:27 AM",
  "baseScore": 6.5,
  "baseScoreVersion": "3.1",
  "baseScoreVector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
  "references": [
    "https://nvd.nist.gov/vuln/detail/CVE-2020-8192",
    "https://github.com/fastify/fastify/commit/74c3157ca90c3ffed9e4434f63c2017471ec970e",
    "https://hackerone.com/reports/903521"
  ],
  "aliases": [
    "CVE-2020-8192",
    "GHSA-xw5p-hw6r-2j98"
  ],
  "assigner": "hackerone",
  "epss": 0.38,
  "enisaIdProduct": [],
  "enisaIdVendor": [
    {
      "id": "dd3a8586-877e-33bc-9316-ec82a8f841ed",
      "vendor": {
        "name": "n/a"
      }
    }
  ]
}